spring:
  application:
    name: ngac-core
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  neo4j:
    uri: bolt://127.0.0.1:7687
    authentication:
      username: neo4j
      password: fJxx2m#@DbWwMW
ngac:
  eventbus:
    async: true
test-api:
  enable: true
server:
  port: 8080