spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.24.131.166:6432/test?currentSchema=pn&rewriteBatchedStatements=true
    username: ltwgtest
    password: y2jF7czkjtW@peqp
    druid:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      #validationQuery: SELECT 1 FROM DUAL #mysql
      validationQuery: SELECT 'x'   #postgresql
      testWhileIdle: false
      testOnBorrow: false
      testOnReturn: false
  application:
    name: ngac-core
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  neo4j:
    uri: bolt://127.0.0.1:7687
    authentication:
      username: neo4j
      password: fJxx2m#@DbWwMW
ngac:
  eventbus:
    async: true
test-api:
  enable: true
server:
  port: 8080